-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 13, 2023 at 06:04 AM
-- Server version: 5.7.39-cll-lve
-- PHP Version: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `prop_majestic`
--
CREATE DATABASE IF NOT EXISTS `prop_majestic` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `prop_majestic`;

-- --------------------------------------------------------

--
-- Table structure for table `about`
--

CREATE TABLE `about` (
  `id` int(10) NOT NULL,
  `title` varchar(100) NOT NULL,
  `content` longtext NOT NULL,
  `image` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `about`
--

INSERT INTO `about` (`id`, `title`, `content`, `image`) VALUES
(10, 'About Our Company', '<div id=\"pgc-w5d0dcc3394ac1-0-0\" class=\"panel-grid-cell\">\r\n<div id=\"panel-w5d0dcc3394ac1-0-0-0\" class=\"so-panel widget widget_sow-editor panel-first-child panel-last-child\" data-index=\"0\">\r\n<div class=\"so-widget-sow-editor so-widget-sow-editor-base\">\r\n<div class=\"siteorigin-widget-tinymce textwidget\">\r\n<p class=\"text_all_p_tag_css\">Welcome to Prop Majestic! Prop Majestic is passionate about helping\r\n          people find their dream homes. With 13+ years of experience in the\r\n          industry, we have developed a deep understanding of the real estate\r\n          market and are committed to providing our clients with the highest level\r\n          of service and expertise.</p>\r\n<p class=\"text_all_p_tag_css\">Our mission is simple, to make your real estate experience as\r\n          stress-free and enjoyable as possible. Whether you are looking to buy,\r\n          sell, or rent a property, we are here to guide you through every step of\r\n          the process. We pride ourselves on our strong communication skills,\r\n          attention to detail, and commitment to achieving the best possible\r\n          results for our clients.</p>\r\n<div id=\"pgc-w5d0dcc3394ac1-0-0\" class=\"panel-grid-cell\">\r\n<div id=\"panel-w5d0dcc3394ac1-0-0-0\" class=\"so-panel widget widget_sow-editor panel-first-child panel-last-child\" data-index=\"0\">\r\n<div class=\"so-widget-sow-editor so-widget-sow-editor-base\">\r\n<div class=\"siteorigin-widget-tinymce textwidget\">\r\n<p class=\"text_all_p_tag_css\">At our real estate agency, we believe that everyone deserves to find\r\n          their perfect home. That’s why we work tirelessly to ensure that our\r\n          clients have access to the most comprehensive and up-to-date listings in\r\n          the area. We take the time to understand your unique needs and\r\n          preferences and will work with you to find a property that meets all of\r\n          your criteria.\r\n          We have more than 180+ projects of different categories like\r\n          residential, rental, commercial, Agricultural Plots, Non-Agricultural\r\n          plots, etc to fulfill all your real estate needs. No matter what your\r\n          real estate needs may be, we are here to help.\r\n          We have more than 180+ projects of different categories like\r\n          residential, rental, commercial, Agricultural Plots, Non-Agricultural\r\n          plots, etc to fulfill all your real estate needs. No matter what your\r\n          real estate needs may be, we are here to help.</p>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', 'condos-pool.png');

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `aid` int(10) NOT NULL,
  `auser` varchar(50) NOT NULL,
  `aemail` varchar(50) NOT NULL,
  `apass` varchar(50) NOT NULL,
  `adob` date NOT NULL,
  `aphone` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`aid`, `auser`, `aemail`, `apass`, `adob`, `aphone`) VALUES
(9, 'admin', 'admin@gmail.com', 'admin', '1999-12-06', '9878786545');

-- --------------------------------------------------------

--
-- Table structure for table `city`
--

CREATE TABLE `city` (
  `cid` int(50) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `sid` int(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `city`
--

INSERT INTO `city` (`cid`, `cname`, `sid`) VALUES
(9, 'navi mumbai', 3),
(10, 'vapi', 2),
(11, 'valsad', 2);

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `cid` int(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `message` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`cid`, `name`, `email`, `phone`, `message`) VALUES
(1, 'vasy', 'bajksdn@gmail.cpom', 'bjaksndks,', 'amsdjkasndkl'),
(2, 'Vasuuuuuu', 'uuuuuu@bbbb.com', '9128398', 'kajsdkj'),
(3, 'purva', 'abc@gmail.com', '8987666789', 'hello'),
(4, 'Somnath Ballal', 'ballalsomnath@gmail.com', '9637449060', 'Hello'),
(5, 'Somnath Ballal', 'ballalsomnath@gmail.com', '9637449060', 'Hello'),
(6, 'Kalyani  Zade', 'kalyanizade121@gmail.com', '7058202551', 'hi');

-- --------------------------------------------------------

--
-- Table structure for table `property`
--

CREATE TABLE `property` (
  `pid` int(50) NOT NULL,
  `title` varchar(200) NOT NULL,
  `pcontent` longtext NOT NULL,
  `type` varchar(100) NOT NULL,
  `bhk` varchar(50) NOT NULL,
  `stype` varchar(100) NOT NULL,
  `bedroom` varchar(50) NOT NULL,
  `bathroom` varchar(50) NOT NULL,
  `balcony` varchar(50) NOT NULL,
  `kitchen` varchar(50) NOT NULL,
  `hall` varchar(50) NOT NULL,
  `floor` varchar(50) NOT NULL,
  `size` varchar(50) NOT NULL,
  `price` varchar(50) NOT NULL,
  `location` varchar(200) NOT NULL,
  `city` varchar(100) NOT NULL,
  `state` varchar(100) NOT NULL,
  `feature` longtext NOT NULL,
  `pimage` varchar(300) NOT NULL,
  `pimage1` varchar(300) NOT NULL,
  `pimage2` varchar(300) NOT NULL,
  `pimage3` varchar(300) NOT NULL,
  `pimage4` varchar(300) NOT NULL,
  `uid` int(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `totalfloor` varchar(50) NOT NULL,
  `date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `property`
--

INSERT INTO `property` (`pid`, `title`, `pcontent`, `type`, `bhk`, `stype`, `bedroom`, `bathroom`, `balcony`, `kitchen`, `hall`, `floor`, `size`, `price`, `location`, `city`, `state`, `feature`, `pimage`, `pimage1`, `pimage2`, `pimage3`, `pimage4`, `uid`, `status`, `totalfloor`, `date`) VALUES
(33, 'Alora', '<p>Welcome to Alora, an inspired edifice that celebrates life. Leisure is the buzzword of life here in Alora. The collage of memories here is filled with blissful moments like leisurely reading a book, sketching sitting beside lush green trees, celebrating community gatherings with friendly neighbours or just a stroll along the curated green lawns.</p>', 'flat', '1,2,3 BHK', 'Rent/sale', '2-3', '2-3', '1-2', '1', '1', '', '800-1500 Sqft', '3.08 Cr', 'Kalina, Santacruz (E) ,Mumbai', 'Mumbai', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type :Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '1676290046319160986.jpg', '1676290061232805390.jpg', '1676367838520015711.jpg', '16762889001986654752.jpg', '16762889991535460527.jpg', 14, 'available', '22 Floor', '2023-04-11 04:19:39'),
(37, 'EVARA', '<p>Prop Majestic Evara is situated at the most admired locations of Mumbai at Borivali West,15 Storeys residences that let you enjoy a &nbsp; lifestyle that&rsquo;s a notch above the ordinary. At Evara accentuate your life with the marvelous feeling of ease, well-being and &nbsp; euphoria at Borivali.</p>', 'flat', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-3', '1', '1', '', '650-1250', '1 Cr', 'Mumbai, Borivali (W)', 'Mumbai', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed&nbsp;</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '2-1.jpg', '2-2.jpg', '2-3.jpg', '2-4.jpg', '2-5.jpg', 14, 'sold out', '22 Floor', '2023-04-11 04:44:34'),
(39, 'Raga', '<p>Welcome to a celebration of life at Raaga &ndash; a gated community that offers a symphony of peaceful residences and community spaces. Located off Hennur Main Road, North Bengaluru, Raaga is in sync with your everyday routine and is close to Manyata Tech Park. Soak up a lifestyle that has been crafted for you, in 2 &amp; 3 BHK residences with a selection of premium and exciting amenities. The Phase - 1 &amp; 2 of Raaga is ready to move in with Occupation Certificate in place.</p>', 'flat', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-2', '1', '1', '', '600-1500', '1.2Cr', 'Raga, Banglore', 'Bangalore', 'Karnataka', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'Raga1.jpg', 'raaga2.jpeg', 'Raga3.jpg', 'Raga4.jpg', 'Raga8.png', 14, 'available', '22 Floor', '2023-04-11 05:36:16'),
(40, '24K GRAZIO', '<p><strong>An experience beyond expectations, created for leaders, visionaries, and stalwarts!</strong></p>\r\n<p><br />Kolte-Patil 24K Grazio is an epitome of luxury, with residences where uncompromising design principles meet meticulous engineering, inspiring architecture, and a legacy of excellence. A place where 24 golden principles converge to let you experience a niche living in the cosmopolitan heart of Bengaluru. Embedded with the finest the world offers, every detail, every amenity, every innovation is envisioned for those who desire for everything, and more! Come, live in the pulse of the city at a residence that&rsquo;s poised to become the most elite gated community in Koramangala.</p>', 'flat', '3 BHK', 'Rent/sale', '3', '2', '2', '1', '1', '', '1900', '1.2Cr', 'Koramangala, Bengaluru', 'Bangalore', 'Karnataka', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '24 K_2.jpg', '24k.jpg', '24k_3.jpg', '24k_4.jpg', '24k_5.jpg', 14, 'available', '22 Floor', '2023-04-11 04:34:11'),
(41, 'JAI VIJAY', '<p>A home that&rsquo;s perfect, in all sense.</p>\r\n<p>Designed by a celebrated architect, Hafeez Contractor, Jai Vijay by Kolte Patil is the one crafted to perfection. Situated at the most admired locations of Mumbai, these homes let you enjoy a lifestyle that&rsquo;s a notch above the ordinary. Spread across 2.25 acres, the largest land bank in Vile Parle, this landmark project ensures proximity to major parts of the city. With all the exclusive features, these 2/3 RLK residential apartments in Vile Parle, Mumbai are the best place to live in and even better place for investment.</p>', 'flat', '1,2,3 BHK', 'Rent/sale', '2-3', '2-3', '1-2', '1', '1', '', '800-1250', '10000000', 'Vile Parle, Mumbai', 'Mumbai', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Appartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '1571402892947679118.jpg', '1571402878931050239.jpg', '1571402864252774507.jpg', '2-4.jpg', '2-5.jpg', 14, 'sold out', '22 Floor', '2023-04-11 04:28:32'),
(42, 'ITOWERS EXENTE', '<p>The winner of coveted real estate awards by prestigious institutions, ITOWERS redefines modern living. The development is equipped with innovations that make your lifestyle perfect. Integrating technology, design, aesthetics &amp; a world of sustainable thinking, ITOWERS starts and ends with your family and you. Perfectly located in the hub of South East Bengaluru, ITOWERS exente is the perfect work - life integration.</p>\r\n<p>&nbsp;</p>\r\n<p>10 min walk to Infosys, GE, TCS, Tech Mahindra, Schneider Electric, HP &amp; many other corporates.</p>\r\n<p>&nbsp;</p>\r\n<p>One of the tallest towers in the vicinity with 3 side open view of the city.</p>\r\n<p>&nbsp;</p>\r\n<p>State of the art amenities like &ndash; 4 gardens, clubhouse with a rooftop pool, Aristotle digital library, squash court, Gym &amp; much more.</p>', 'flat', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-2', '1', '1', '', '600-1500', '98L', 'Electronic City, Bengaluru', 'Bangalore', 'Karnataka', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'itower2.jpg', 'Itowers1.jpg', 'itowers3.jpg', 'itowers6.jpg', 'itowewrs5.jpg', 14, 'available', '22 Floor', '2023-04-11 05:30:34'),
(46, 'VAAYU', '<p>Immaculately designed and well appointed 1 &amp; 2 BHK homes cater to each and every nuances of luxury living in the safe and secure habitat of Dahisar West. To take in the best of nature in all seasons, these fine apartments are constructed in the east-west pattern.<br />Gusts of pleasantly cool Vaayu will easily flow through and circulate cool air so that wide, nature frame windows remain open throughout. Two sophisticated towers are tactically planned and strategically placed. At Vaayu, you simply rise above.</p>', 'flat', '1,2 BHK', 'Rent/sale', '1-2', '1-2', '1-2', '1', '1', '', '650-850', '1.75 Cr', 'Mumbai, Next to IC Colony, Dahisar (W)', 'Mumbai', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Appartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '4-5.jpg', '4-4.jpg', '4-1.jpg', '4-2.jpg', '4-3.jpg', 14, 'available', '22 Floor', '2023-04-11 04:33:24'),
(47, 'MIRABILIS', '<p>Slow down and appreciate life at the most-anticipated flats in Bangalore. Located just off Horamavu Main Road, Mirabilis by Kolte-Patil Developers has seven pristine white towers nestled amidst lush greenery with a natural lake nearby. Every aspect here has been designed tastefully and the amenities here encourage community and neighbourly interaction at all levels and age groups. The magnificent and spacious 1 BHKs with a private layout of the interiors await you at Mirabilis.</p>', 'flat', '1 BHK', 'Rent/sale', '1', '1', '1', '1', '1', '', '550', '35L', 'Bangalore Residential', 'Bangalore', 'Karnataka', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Flat</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'Mira3.jpg', 'mira4.jpg', 'mira5.webp', 'Miracle3.jpg', 'Mira1.jpg', 14, 'available', '22 Floor', '2023-04-11 05:23:47'),
(48, 'Life Republic', '<p>Situated just 4.5 kilometers away from Hinjawadi, the IT hub of Pune, Kolte Patil Life Republic is a 393 acres integrated township with undulating greens. Designed with one single objective: to create future-proof spaces and a meaningful way of life for the thinking minds, it is a community built for all. Built with core values of creativity, sensitivity and sustainability, every sector of this award-winning township project in Pune offers you a luxurious lifestyle. Step into a life of inclusion; of freedom and expression; of sustainability and sensitivity; of democratic values and good governance; of ancient wisdom and modern conveniences.</p>', 'appartment', '1,2,3,4 BHK', 'Rent/Sale', '1-4', '1-4', '1-4', '1', '1', '', '750-1750', '2.5 Crore', 'Hinjewadi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>Newly Constructed</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '1609390324894047904.jpg', 'maxresdefault.jpg', '1607670104268037680.jpg', '16076701241467255864.jpg', '16076701431605539376.jpg', 14, 'available', '22 Floor', '2023-04-11 03:51:34'),
(49, 'Little Earth', '<p>A finely crafted 2 &amp; 3 BHK home here, promises a lot more than just a good living. It&rsquo;s a bouquet of goodies! An enticing expanse of 25 acres, a gated community, serene environment, eye-pleasing open spaces, 5 clubhouses and 30+ lifestyle amenities, a 72 feet wide private boulevard, the smart mix of retail spaces &amp; commercials and much more&hellip;No wonder 450+ families have already chosen this one-of-its-kind living paradise as their home. And now for the upcoming phases, the life is going to be even more exciting.</p>', 'appartment', '1,2,3 BHK', 'Rent/Sale', '1-3', '1-3', '1-2', '1', '1', '', '1550', '60L', 'Kiwale-Mamurdi Road', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>Newly Constructed</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'fs.jpeg (1).webp', '16678815302064496158.jpg', '1667882003182510677.jpg', 'Blog2-2.jpg', '1667881984935633376.jpg', 14, 'available', '22 Floor', '2023-04-11 03:51:34'),
(50, 'Equa', '<p>Inspired by the philosophy of a new beginning, EQUA offers thoughtfully planned spaces where you can experience a magnificent sunrise; an amber sunset; the tranquillity of a glistening night. Well planned, breezy and well-ventilated homes will give you an incredible living experience. Vastu Compliant Homes, Spacious lobby on every floor, Minimum Dead Spaces and lesser homes per floor are some of USPs of the homes here at EQUA.</p>', 'flat', '2 BHK', 'Rent/Sale', '2', '2', '1-2', '1', '1', '', '850', '45 L', 'Kharadi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>Newly Constructed</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Flat</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '1638793270454279814.jpg', '16387932811204863024.jpg', '1638793260581209912.jpg', '1638793246397419888.jpg', 'web11.jpg', 14, 'available', '22 Floor', '2023-04-11 03:51:34'),
(51, ' Ivy Estate', '<p><br />Nestled in Wagholi, east Pune&rsquo;s hottest investment location, Kolte Patil IVY Estate offers you community living along with green living. These spacious 1, 2 &amp; 3 RLK homes in Pune are efficiently planned and thoroughly crafted to satiate all your needs and desires. Right from kids to elder people, everyone will experience a refreshing life at Ivy Estate. Along with this, the flourishing infrastructure and excellent connectivity add to its beauty.</p>', 'bungalow', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-2', '1', '1', '', '850-1600', '35.91 L', 'Wagholi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>Newly Constructed</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Bungalow</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '16038787391104159735.jfif', '1603878689460929548.jfif', '16038788231259477126.jfif', '16038786102103425728.jfif', '1603878771416071373.jfif', 14, 'available', '2 Floor', '2023-04-11 22:27:49'),
(52, ' 24K Stargaze', '<p>24K Stargaze by Kolte Patil, not only offers you a place to reside but a home where you&rsquo;ll enjoy every moment with your friends and family. Located in Bavdhan, which is just 5-kms away from Kothrud, this residential project lets you enjoy excellent connectivity, while you stay amidst nature and away from chaos. From sparkling city landscapes on one side to mesmerising hill views on other side, this place is perfect to create beautiful memories with your loved ones.</p>', 'appartment', '1,2,3,4 BHK', 'Rent/sale', '1-4', '1-4', '1-4', '1', '1', '', '650-1750', ' 1.9 Cr', 'Bavdhan ', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : </span>Newly Constructed</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '15632599341890939634.jpg', '15629139802055582996.jpg', '15712947911950551591.jpg', '1571294922442956750.jpg', '15629139522066351578.jpg', 14, 'available', '22 Floor', '2023-04-11 03:58:20'),
(53, ' 24K OPULA', '<p>Spread across 7.77 acres, each home at 24K Opula is built to perfection and adheres to the highest standards of quality and efficiency. The ongoing project in Pune by Kolte Patil Developers offers exclusive 3 and 4 BHKs with designer sundecks. These luxurious apartments are adorned with Europe&rsquo;s biggest brands - Porcelanosa, Noken and GamaDecor. 24K Opula makes the most of available space in terms of friendliness and aesthetics. The project is certified with IGBC Green Homes reflecting on our philosophy of building sustainable homes. Come live a lavish life at 24K Opula.</p>', 'flat', '1,2,3,4 BHK', 'Rent/sale', '1-4', '1-4', '1-4', '1', '1', '', '763-1850', '1.87 Cr.', 'Pimple Nilakh', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age :Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Flat</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '8261609051488381887.jpg', '1603877098658856621.jpg', '703e0f72b4d118de26ee0914f43279c1.jpg', 'dfshtsere.jfif', '16038768132114886512.jpg', 14, 'available', '22 Floor', '2023-04-11 04:02:53'),
(54, '24K ATRIA', '<p>Beautifully crafted to complement your chic and aristocratic personality, our exclusively designed residences at 24K Atria by Kolte-Patil Developers let you explore the true joy of grandeur. These ultra-lavish flats in Pune, with just two apartments on each floor, ensure complete privacy at all times. The ongoing project in Pune offers you the perks of smart living with cutting-edge home automation and electronic systems. Relax, rejuvenate, entertain or simply sip champagne with the cr&egrave;me-de-la-cr&egrave;me of society. Come, live exclusive. Only at 24K Atria.</p>', 'appartment', '1,2,3,4 BHK', 'Rent/sale', '1-4', '1-4', '1-4', '1', '1', '', '650-1850', ' 3.88 Cr', 'Pimple Nilakh', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'unnamed.png', '15712164951478616947.jpg', '15712166401451688452.jpg', '1574345006517659039.jpg', '15712166981043720046.jpg', 14, 'available', '22 Floor', '2023-04-11 04:06:04'),
(55, '24K Sereno', '<p>Kolte-Patil Developers introduce 24K Sereno along with NOW Realty. The super luxurious flats in Baner are a new residential landmark in the premium residential and commercial hub. The ongoing project in Pune is yet another feather in the cap of the signature 24K brand. It offers the perfect blend of both worlds - the 24K life and a serene living experience. The premium 2 &amp; 3 RLK apartments are embellished with charismatic features that will facilitate its dwellers with an extravagant, enriching and luxurious lifestyle. Magnificently drafted to appeal to the rich taste of contemporary home buyers, it&rsquo;s thoughtfully laid out design and pristine surrounding ensure that you are surrounded with nothing but the best.</p>', 'appartment', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-2', '1', '1', '', '1350', '1.90 Cr', 'Baner', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', 'eea2a1de627ca90d1bb1493c19762814.png', 'gimg7.jpg', 'new_5147823651558415763.jpg', '15713840181788875417.jpg', '1571383981444931073.jpg', 14, 'available', '22 Floor', '2023-04-11 04:09:49'),
(56, 'Three Jewels Moonstone', '<p>Inspired by positive energies, Moonstone by Kolte-Patil Developers is a haven for those who appreciate peace and tranquility. Each corner of this beautiful gated community is designed to spark creativity while enhancing relationships. Spacious, breezy and well-ventilated rooms with mesmerizing views makes living here an incredible experience. The ongoing project in Pune offers you 1, 2 and 3 BHKs which are bathed in natural light and are designed to make you feel special. Over 300 happy families reside here and are waiting to welcome you to this upgraded lifestyle.</p>', 'appartment', '2 BHK', 'Rent/sale', '2', '2', '1-2', '1', '1', '', '863', ' 60 L', 'Katraj-Kondwa', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '15719236431035755117.jpg', '355kolte-patil-three-jewels-project-large-image11-thumb2.jpg', '1563192072_Kolte_Patil_Three_Jewels_Phase_2_elevation_Image.jpg', 'JLL_PUN_Three_jewels_Moonstone_17_ELV_1.jpg', '1571316863131572092.jpg', 14, 'available', '22 Floor', '2023-04-11 04:15:12'),
(57, ' Green Olive', '<p>Spread over 6 acres of land, this residential project in Pune offers you a neighborhood that houses the biggest IT hub of India, Rajiv Gandhi Infotech Park. Located in Hinjewadi, these luxurious and elegantly designed 2 &amp; 3 BHK homes by Kolte-Patil Developers are everything that you have always wanted in a home. With their contemporary style, intelligent use of space and supreme comfort, these premium flats in Pune are full of pleasant surprises.</p>', 'appartment', '3 BHK', 'Rent/sale', '3', '3', '3', '1', '1', '', '1250', '67 L', 'Hinjewadi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '15713900371570054893.jpg', '15713900821382864932.jpg', '15713900621776175143.jpg', '688q4qky.jpg', '8a9fa15077e24f110177e2eb3a9952da_83395_938116_large.jpg', 14, 'available', '22 Floor', '2023-04-11 04:18:44'),
(58, ' Tuscan Parkland', '<p>For the life you&rsquo;ve achieved, you deserve a lifetime of unique luxury. Tuscan Parkland by Kolte-Patil Developers provides you with a luxury at&nbsp;every nook and corner. The ongoing project in Pune is built on the philosophy of ultramodern luxury, intricately planned home spaces and design innovations that enable a rich, satisfying life that is never devoid of the very finest. These uber luxurious 3 BHK flats in Pune are designed in a fashion that welcome nature inside. Experience lavish spaces that enjoy endless possibilities where even the sky is limitless.</p>', 'appartment', '3 BHK', 'Rent/sale', '3', '1-3', '1-2', '1', '1', '', '1450', '1.37 Cr', 'Kharadi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '15719262702102813772.jpg', '20190515110220_city-T.jpg', '15719238281630968496.jpg', '15719262911875006331.jpg', '13032021032748_971567_tuscan-banner---Copy.jpg', 14, 'available', '22 Floor', '2023-04-11 04:23:52'),
(59, 'Universe', '<p>The {U}niverse is the cradle of a digital lifestyle. Powered by the digital living solutions you will be ensconced at the heart of every activity here. The Planet App, a proprietary digital platform of Planet Smart City facilitates a safe, social and service-rich urban environment where citizens share and cooperate &ndash; improving quality of life</p>\r\n<p>&nbsp;</p>\r\n<p>- Project Spread Across 4.164 Hectares (~10.5 Acres)</p>\r\n<p>- 40% Open And Landscaping Area</p>\r\n<p>- Social Innovation Programmes</p>\r\n<p>- Enhanced Technological Solutions In Networks, Air Quality Monitoring And Security</p>\r\n<p>- Smart And Socially Inclusive Neighbourhoods That Empower Citizens To Make A Difference To Their Local Community.</p>\r\n<p>- Prominent Location Within Life Republic</p>\r\n<p>- A Plethora Of Sustainable Solutions Like Urban Gardens, The Use Of Native Plants, Community Composting, Among Others&nbsp;</p>', 'flat', '1,2 BHK', 'Rent/sale', '1-2', '1-2', '1-2', '1', '1', '', '650-850', '36 L', 'Hinjawadi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Flat</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '16076699362054117562.jpg', '16076700761887896555.jpg', '3.jpg', '4.webp', '1143111223.webp', 14, 'available', '22 Floor', '2023-04-11 04:26:50'),
(60, 'Western Avenue Twin Towers', '<p>Kolte Patil Western Avenue is a perfect blend of modern architecture and beautifully carved out collaborative community spaces. Here, you don&rsquo;t compromise on quality and experience the environmental sensitivity with beautiful living spaces equipped by excellent amenities. For commute, you have easy accessibility to the Pune-Mumbai Highway at Wakad. Come, live the fuller life, you always aspired at the 2 &amp; 3 RLK homes in Wakad at Western Avenue.</p>', 'appartment', '1,2,3 BHK', 'Rent/sale', '1-3', '1-3', '1-2', '1', '1', '', '750-1350', '79 L', 'Wakad', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age :Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '15629110951924295292.jpg', '1562911082294930768.jpg', '15629110651241169476.jpg', '1571297549353807847.jpg', '15712975741642681301.jpg', 14, 'available', '22 Floor', '2023-04-11 04:31:04'),
(61, 'Centria', '<p>It&rsquo;s time to give those gadgets a rest, look up and beyond to be spellbound at the most anticipated flats in Pune. Login to life as you step into your ultra-premium 3 BHK home at Centria. Somewhere in the heart of Undri, Kolte-Patil Developers have created just the right place for you! Live life at its best in garden apartments with world class amenities, smart space utilization, ample sunlight, cross ventilation and artificial lawn gardens that open to the sky with access from all rooms apart from a private backyard. Embrace your dreams, hopes and aspirations as you take one step into the the best residential project in Pune.</p>', 'appartment', '3 BHK', 'Rent/sale', '3', '3', '3', '1', '1', '', '1350', '99 L', 'NIBM-Undri Road', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '16151842632010822343.jpg', '16124472881698046674.jpg', '16151844301308234311.jpg', '1615184504841091923.jpg', '16151845311969333571.jpg', 14, 'available', '22 Floor', '2023-04-11 04:35:11'),
(62, ' Mount Castle', '<p>Gift yourself the best that you could. Experience the glory of life through our wondrous creation designed keeping \"You and your home\" in mind. We present to you, Mount Castle - the affordable, comfortable and suitable residential project with</p>\r\n<ul>\r\n<li>Ready amenities.</li>\r\n<li>Prime location with excellent connectivity.</li>\r\n<li>Proximity to commercial hubs.</li>\r\n<li>Highly developed social infrastructure.</li>\r\n<li>Budget-friendly investment options.</li>\r\n<li>Steady value appreciation of property.</li>\r\n</ul>', 'appartment', '1,2 BHK', 'Rent/sale', '1-2', '1-2', '1-2', '1', '1', '', '650-850', '29 L', 'Wagholi', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '16038645841549496342.png', '1603863981251806129.png', '16038644803621216.png', '1603862092520161632.png', '1603864548708583267.png', 14, 'available', '22 Floor', '2023-04-11 04:38:00');
INSERT INTO `property` (`pid`, `title`, `pcontent`, `type`, `bhk`, `stype`, `bedroom`, `bathroom`, `balcony`, `kitchen`, `hall`, `floor`, `size`, `price`, `location`, `city`, `state`, `feature`, `pimage`, `pimage1`, `pimage2`, `pimage3`, `pimage4`, `uid`, `status`, `totalfloor`, `date`) VALUES
(63, ' City Avenue', '<p>City avenue is located along the Mumbai -Bangalore highway at Wakad and is accessible by a 12m to 24m wide DP road. Wakad is one of the fastest growing suburbs of Pune and has become the ideal Residential &amp; Commercial destination for the city. Its proximity to the bustling info tech and biotechnology hub of Hinjawadi has contributed to its phenomenal growth.</p>', 'commercial', 'Office space', 'Rent/sale', '0', '2', '0', '0', '0', '', '735-1100', '1.50Cr', 'Hinjewadi, Pune', 'Pune', 'Maharashtra', '<p>&nbsp;</p>\r\n<!---feature area start--->\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Property Age : Newly Constructed</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Swiming Pool : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">GYM : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Type : Commercial</span></li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Security : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-secondary font-weight-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>\r\n<!---feature area end---->\r\n<p>&nbsp;</p>', '16202916911507712368.jpeg', 'kolte-patil-city-avenue-project-project-large-image1.jpg', '1.jpg', '1573032492431493956.jpg', '1573032505640629906.jpg', 14, 'available', '22 Floor', '2023-04-11 22:48:09');

-- --------------------------------------------------------

--
-- Table structure for table `state`
--

CREATE TABLE `state` (
  `sid` int(50) NOT NULL,
  `sname` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `state`
--

INSERT INTO `state` (`sid`, `sname`) VALUES
(2, 'gujarat'),
(3, 'goa'),
(4, 'maharashtra'),
(7, 'bihar'),
(9, 'chhattisgarh'),
(10, 'uttar pardesh'),
(15, 'rajasthan');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `uid` int(50) NOT NULL,
  `uname` varchar(100) NOT NULL,
  `uemail` varchar(100) NOT NULL,
  `uphone` varchar(20) NOT NULL,
  `upass` varchar(50) NOT NULL,
  `utype` varchar(50) NOT NULL,
  `uimage` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`uid`, `uname`, `uemail`, `uphone`, `upass`, `utype`, `uimage`) VALUES
(14, 'admin', 'admin@gmail.com', '9876543210', 'admin', 'user', '3.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `about`
--
ALTER TABLE `about`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`aid`);

--
-- Indexes for table `city`
--
ALTER TABLE `city`
  ADD PRIMARY KEY (`cid`);

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`cid`);

--
-- Indexes for table `property`
--
ALTER TABLE `property`
  ADD PRIMARY KEY (`pid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `cid` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `property`
--
ALTER TABLE `property`
  MODIFY `pid` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
